### ISSUE TITLE
Ability to define additional keys based on columns in CSV

### ISSUE THREAD

**Issue by homebysix** [nmcspadden/ManifestCreator#2]
Currently ManifestCreator works well with a simple list of serial numbers in CSV format:

| serial |
| --- |
| ABCDEF12343GH |
| IJKLM21253OPQ |
| RSTUV125123WX |

It would be ~~good~~ mind-blowingly wonderful if you could specify additional manifest keys as columns and have ManifestCreator include them in the manifests it generates.

| serial | display_name | user |
| --- | --- | --- |
| ABCDEF12343GH | Al's MacBook Air | Albert Anderson |
| IJKLM21253OPQ | Becca's Box | Rebecca Brown |
| RSTUV125123WX | CharlesMBP | Charles Crawford |

For example, the first manifest generated by the above CSV would be named **ABCDEF12343GH** and would contain:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>display_name</key>
    <string>Al's MacBook Air</string>
    <key>user</key>
    <string>Albert Anderson</string>
</dict>
</plist>
```

**Comment by nmcspadden** [comment]
I have no objection to this, but these aren't standard keys for manifests. I didn't realize anyone had a use case for arbitrary keys in manifests, but if it doesn't break anything, I'm all for it.

**Comment by homebysix** [comment]
Well, they're arbitrary-ish. [MunkiAdmin uses](https://github.com/hjuutilainen/munkiadmin/blob/551e2eb123b37fa7f2512bb59cd93ace5beb0b4e/MunkiAdmin/UserDefaults.plist#L15-L16) **display_name** and **user** to display columns in the manifest view, which is often helpful to sorting and searching manifests.
